// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwbpceepjapxsjlgrjbe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3YnBjZWVwamFweHNqbGdyamJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTM1NTcsImV4cCI6MjA2ODY2OTU1N30.yZVGbZ-yPs8cEmQ0d2hNN5F7gvjxht9ISM689HJTyCo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});